name: CI/CD Pipeline

on:
  push:
    branches:
      - '**' # Trigger on push to any branch

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Get branch name
        id: get-branch
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-')" >> $GITHUB_ENV

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true
          cache-dependency-path: go.sum
      
      - name: Install templ
        run: |
          go install github.com/a-h/templ/cmd/templ@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'app/package-lock.json'
      
      - name: Verify Node installation
        run: |
          echo "Node version: $(node --version)"
          echo "npm version: $(npm --version)"
          echo "PATH: $PATH"
      
      - name: Setup Static Files and Node Dependencies
        run: |
          set -e # Exit immediately if a command exits with a non-zero status.
          mkdir -p app/static/css
          cd app
          # Ensure package.json exists and install dependencies
          if [ ! -f package.json ]; then
            echo "Creating package.json..."
            npm init -y
          fi
          npm install -D tailwindcss postcss autoprefixer
          npx tailwindcss init -p
          # Create Tailwind CSS file if it doesn't exist
          if [ ! -f ./static/css/styles.css ]; then
            echo "@tailwind base;" > ./static/css/styles.css
            echo "@tailwind components;" >> ./static/css/styles.css
            echo "@tailwind utilities;" >> ./static/css/styles.css
          fi
          npx tailwindcss -i ./static/css/styles.css -o ./static/css/output.css
          cd ..
          touch app/static/.gitkeep
          chmod -R 755 app/static
      - name: Generate templates
        run: cd app && templ generate -path ./views && cd ..
      - name: Build
        run: ls && go build ./...
      - name: Test
        run: go test ./...

      - name: Check for AWS Credentials
        id: check-aws-creds
        run: |
          if [ -n "$AWS_ACCESS_KEY_ID" ] && [ -n "$AWS_SECRET_ACCESS_KEY" ]; then
            echo "AWS credentials detected"
            echo "has_creds=true" >> $GITHUB_OUTPUT
          elif [ -n "${{ secrets.AWS_ACCESS_KEY_ID }}" ] && [ -n "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
            echo "GitHub secrets detected"
            echo "has_creds=true" >> $GITHUB_OUTPUT
          else
            echo "No AWS credentials found - running in local test mode"
            echo "has_creds=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and Test Only
        if: steps.check-aws-creds.outputs.has_creds == 'false'
        run: |
          echo "Running in local test mode - skipping AWS deployment steps"
          echo "Build and test completed successfully"

      - name: Configure AWS credentials
        if: steps.check-aws-creds.outputs.has_creds == 'true'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID || env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY || env.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        if: steps.check-aws-creds.outputs.has_creds == 'true'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image
        if: steps.check-aws-creds.outputs.has_creds == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/transgo-${{ env.BRANCH_NAME }}:${{ github.sha }},${{ steps.login-ecr.outputs.registry }}/transgo-${{ env.BRANCH_NAME }}:latest
          file: ./Dockerfile

      - name: Create Terraform environment directory
        if: steps.check-aws-creds.outputs.has_creds == 'true'
        run: |
          mkdir -p infra/terraform/environments/${{ env.BRANCH_NAME }}
          cp infra/terraform/environments/template/* infra/terraform/environments/${{ env.BRANCH_NAME }}/

      - name: Setup Terraform
        if: steps.check-aws-creds.outputs.has_creds == 'true'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        if: steps.check-aws-creds.outputs.has_creds == 'true'
        run: |
          cd infra/terraform/environments/${{ env.BRANCH_NAME }}
          terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Terraform Apply
        if: steps.check-aws-creds.outputs.has_creds == 'true'
        id: terraform-deploy
        run: |
          cd infra/terraform/environments/${{ env.BRANCH_NAME }}
          terraform apply -auto-approve
          echo "task_definition_arn=$(terraform output -raw task_definition_arn)" >> $GITHUB_OUTPUT
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Deploy to ECS
        if: steps.check-aws-creds.outputs.has_creds == 'true'
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.terraform-deploy.outputs.task_definition_arn }}
          service: transgo-service
          cluster: transgo-cluster-${{ env.BRANCH_NAME }}
          wait-for-service-stability: true
