name: Build and Push Container
on:
  push:
    branches: [dev]
    paths:
      - 'app/**'
      - 'Dockerfile'
      - 'build.sh'
      - 'docker-compose.yml'

env:
  ECR_REGISTRY: 948845146147.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: transgo-app
  IMAGE_TAG: dev-${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and tag the image
        run: |
          ./build.sh
          docker-compose build
          docker tag transgo-app:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push image to Amazon ECR
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
