name: Deploy to Dev Environment

on:
  push:
    branches: [ main, test ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: transgo-dev
  ECS_SERVICE: transgo-service
  ECS_CLUSTER: transgo-cluster-dev
  ECS_TASK_DEFINITION: ${{ github.workspace }}/updated-task-definition.json

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
          docker build -t ${{ env.ECR_REPOSITORY }} .
          IMAGE_TAG=$(echo ${{ github.sha }} | cut -c1-7)
          docker tag ${{ env.ECR_REPOSITORY }}:latest ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
          echo "IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Register new task definition
        run: |
          aws ecs register-task-definition \
            --family ${{ env.ECS_CLUSTER }} \
            --network-mode awsvpc \
            --requires-compatibilities FARGATE \
            --cpu 256 \
            --memory 512 \
            --execution-role-arn ecsTaskExecutionRole \
            --container-definitions '[{
              "name": "transgo-app",
              "image": "${{ env.IMAGE_URI }}",
              "essential": true,
              "portMappings": [{
                "containerPort": 80,
                "hostPort": 80
              }]
            }]'

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster ${{ env.ECS_CLUSTER }} \
            --service ${{ env.ECS_SERVICE }} \
            --task-definition ${{ env.ECS_CLUSTER }} \
            --force-new-deployment

      - name: Get ALB DNS name
        id: alb-dns
        run: |
          DNS_NAME=$(aws elbv2 describe-load-balancers --names transgo-alb-dev --query 'LoadBalancers[0].DNSName' --output text)
          echo "ALB_DNS_NAME=$DNS_NAME" >> $GITHUB_OUTPUT
          echo "Application URL: http://$DNS_NAME"

      - name: Output ALB DNS
        run: |
          echo "Application deployed to: http://${{ steps.alb-dns.outputs.ALB_DNS_NAME }}"
