name: Pulumi Deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - 'infra/s3/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Set up Pulumi
        uses: pulumi/actions@v4
        with:
          pulumi-version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies
        working-directory: infra/s3
        run: go mod download

      - name: Pulumi up
        working-directory: infra/s3
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
        run: |
          pulumi stack select dev
          pulumi import aws:s3/bucket:Bucket transgo-media-backend transgo-media-backend-064bcea || true
          pulumi up --yes --stack dev
