name: ECS Deploy

on:
  workflow_call:
    inputs:
      cluster_name:
        description: 'ECS cluster name'
        type: string
      service_name:
        description: 'ECS service name'
        type: string
      task_definition_arn:
        description: 'ARN of the ECS task definition'
        type: string
      image_uri:
        description: 'URI of the Docker image in ECR'
        type: string
      aws_access_key_id:
        description: 'AWS Access Key ID'
        type: string
      aws_secret_access_key:
        description: 'AWS Secret Access Key'
        type: string
      aws_region:
        description: 'AWS Region'
        type: string
        default: 'us-east-1'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_region }}

    - name: Update ECS service
      run: |
        aws ecs update-service \
          --cluster ${{ inputs.cluster_name }} \
          --service ${{ inputs.service_name }} \
          --task-definition ${{ inputs.task_definition_arn }} \
          --force-new-deployment
