name: Docker Build and Push

on:
  workflow_call:
    inputs:
      ecr_repository_name:
        description: 'Name of the ECR repository'
        type: string
      image_tag:
        description: 'Tag for the Docker image'
        type: string
      aws_access_key_id:
        description: 'AWS Access Key ID'
        type: string
      aws_secret_access_key:
        description: 'AWS Secret Access Key'
        type: string
      aws_region:
        description: 'AWS Region'
        type: string
        default: 'us-east-1'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      run: |
        docker build -t ${{ inputs.ecr_repository_name }} .
        docker tag ${{ inputs.ecr_repository_name }}:latest ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr_repository_name }}:${{ inputs.image_tag }}
        docker push ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr_repository_name }}:${{ inputs.image_tag }}
        echo "IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr_repository_name }}:${{ inputs.image_tag }}" >> $GITHUB_ENV
